worcestertechnicalhighschool/techhigh.us

_includes/footer.html, _sass/style.scss, _sass/techhigh.scss
still needs work but it should look better
=> footer rework

_alden_academy/adv-manufacturing.md, _alden_academy/auto-collision.md, _alden_academy/auto-tech.md, _alden_academy/drafting.md, _alden_academy/robotics.md, _alden_academy/welding.markdown, _allied_academy/allied-health.markdown, _allied_academy/biotechnology.markdown, _allied_academy/cosmetology.md, _allied_academy/early-childhood.markdown, _allied_academy/environmental.markdown, _allied_academy/veterinary-assisting.markdown, _construction_academy/carpentry.md, _construction_academy/electrical.md, _layouts/department.html, _sass/techhigh/templates/department.scss
Reverts worcestertechnicalhighschool/techhigh.us#186
=> Revert "sass/edits"

_allied_academy/allied-health.markdown, _allied_academy/cosmetology.md
Fixed bullet points on allied health and cosmetology pages. They are now spaced normally.
=> Changes to Allied Health & Cosmetology pages.

_layouts/contact-us.html, _learn_more/contact-us.md, _posts/summer-work/history-work.md, _sass/techhigh/templates/contact-us.scss
Unfinished. Need to add security code.
=> Contact Form

_allied_academy/early-childhood.markdown, _featured_news/meet-principal-weymouth.md, _posts/summer-work/english-work.md, _public_services/print-shop.markdown, _public_services/skyline-bistro.md, _sections/learn-more.md, _sections/public-services.md, _student_life/clubs.markdown, _technical_areas/itbs-academy.md
Because I have nothing better to do with my time over here at Wilson, I have decided to go over the entire project and fix all the spelling errors, which there were a lot of.
To help prevent future spelling errors, I recommend using the VSCode extension I used to find these spelling errors: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
=> Fix spelling errors

Gemfile.lock, _student_life/student-job-board.md
Created content with a link to the external job board site.
=> link added to job board page

_data/faculty.csv, _technical_areas/alden-academy.md, _technical_areas/allied-academy.md, _technical_areas/construction-academy.md, _technical_areas/itbs-academy.md
Added Mr. Weymouth's picture on faculty page. Also added pictures for technical areas.
=> Added back some pictures

_student_life/athletics.md, _student_life/clubs.markdown, _student_life/freshman.markdown, _student_life/special-ed.md
Could not find the images for Student Job Board and Summer Work. Will search for them more later or find alternate image.
=> Added 4/6 images to the student life page

_student_life/student-job-board.md, _student_life/summer-work.md
We found the images on Joe's computer.
=> Added the last 2 images to the student life page.

assets/inc/paladin-contact/api.js
Use async/await instead of `new Promise` and use `console.error()`.
=> Use async/await and `console.error()`

_layouts/faculty.html
Made comments explaining how the forloop works.
=> Made documentation for the monster forloop I made

_parents_and_community/pac.md
=> Contact page

_allied_academy/cosmetology.md, _construction_academy/electrical.md, _itbs_academy/culinary-arts.markdown, _itbs_academy/graphic-comms.md, _itbs_academy/issn.md, _sass/techhigh/templates/department-pages.scss
added the image for the electrical alumni spotlight
=> Electrical Alumni

_layouts/front-page.html, _sass/techhigh/events.scss, _sass/techhigh/front-page/front-page.scss
I also changed the names of calendar modes to be more "professional".
=> Changed color of calendar text on main page.

_sass/techhigh/templates/department-pages.scss
=> Alumni image fix

_layouts/automotive-services.html, _public_services/automotive-services.markdown, _sass/techhigh/templates/public-services.scss
Added new content and changed a few other things to improve the overall design of the page.
=> Automotive page rework

Gemfile.lock, _sass/techhigh/templates/public-services.scss
Fixed the pages for automotive
=>  Automotive mobile fix

_layouts/salon.html, _public_services/salon.md, _sass/techhigh/templates/public-services.scss
The Desktop page is going to be a different layout but for now this works on mobile. The images are not final either they need to be changed.
=> Layout for the Salone Page (Mobile)

_sass/techhigh/templates/public-services.scss
moves up dotted line on the Salon menu.
=> Salon menu dotted line edit

_layouts/front-page.html, _sass/techhigh/cards.scss, _sass/techhigh/front-page/front-page.scss, _sass/techhigh/front-page/mission.scss, _student_life/clubs.markdown
Completed all home page requests in techhigh.us. I also added the new cta cards Mr. LeBoeuf made for Admissions, Faculty, and Contact Us.
=> Front Page Update

_sass/techhigh/templates/athletics.scss
Reverts worcestertechnicalhighschool/techhigh.us#481
=> Revert "Athletics - Coach info section"

_sass/techhigh/templates/athletics.scss, _student_life/athletics.md
- Fixed alignment of the sports on the athletics page
=> athletics fixes

_layouts/faculty.html, _learn_more/admissions.md
Changed Admission Application to now be closed.
=> emergency change

_layouts/admissions.html, _sass/techhigh/templates/admission.scss
Last minute rush change to the code. It's working. Fingers crossed
=> changed video approach to youtube embed

.hintrc, _data/faculty.csv, _includes/header.html, _parents_and_community/pac.md, _sass/techhigh/header.scss, search.json
-Visual improvement for both mobile and desktop
-Functional improvement for searching function
-Fixed bug in search.json file
=> Search bar improvement

_includes/header.html, _sass/techhigh/header.scss
Enhanced usability implemented
=> Polished the search modal

_includes/header.html
Auto focus added to search modal input field
=> focus added

_includes/header.html, _sass/techhigh/cards.scss
=> fixed cta card titles being too large

_data/faculty.csv, _includes/header.html, _layouts/default.html, _layouts/search.html, _sass/techhigh/btn.scss, _sass/techhigh/header.scss, _sass/techhigh/search.scss, search.json
polished UX
custom search
fixed header and tabindexing
=> Search Updates

_alden_academy/adv-manufacturing.md, _alden_academy/drafting.md, _alden_academy/welding.markdown, _allied_academy/cosmetology.md, _allied_academy/early-childhood.markdown, _allied_academy/environmental.markdown, _allied_academy/veterinary-assisting.markdown, _itbs_academy/culinary-arts.markdown, _itbs_academy/finance-marketing.markdown, _itbs_academy/graphic-comms.md, _itbs_academy/hospitality.markdown, _itbs_academy/issn.md, _itbs_academy/webdev.markdown
Added six images to all shops in Alden, Allied, and ITBS Academies in their Markdown files, along with descriptions for all images.
=> Alden, Allied, ITBS academy images.

_config.yml, _sass/techhigh/templates/department-pages.scss, _sass/techhigh/templates/summer-work.scss, _student_life/freshman.markdown, _summer_work/english.md, _summer_work/history.md, _summer_work/math.md, _summer_work/science.md
Replaced the academics summer work with their recent assignments. Also changed the look of the summer work template so that it doesn't look weird.
=> Summer Work Changes.

_academics/english.markdown, _academics/history.markdown, _academics/math.markdown, _academics/science.markdown, _academics/special-ed.md, _alden_academy/adv-manufacturing.md, _alden_academy/auto-collision.md, _alden_academy/auto-tech.md, _alden_academy/drafting.md, _alden_academy/robotics.md, _alden_academy/welding.md, _allied_academy/allied-health.markdown, _allied_academy/biotechnology.markdown, _allied_academy/cosmetology.md, _allied_academy/early-childhood.markdown, _allied_academy/environmental.markdown, _allied_academy/veterinary-assisting.markdown
added tags and redirect-from to all academics markdown files, alden academy markdown files, and allied academy markdown files. also moved special education from student life to academics.
=> tags, redirect-from, special ed

_construction_academy/carpentry.md, _construction_academy/electrical.md, _construction_academy/painting-and-design.md, _itbs_academy/webdev.markdown
some things were misaligned. fixed them.
=> quick fixes

_academics/special-ed.md, _layouts/faculty.html, _layouts/front-page.html, _layouts/library.html, _parents_and_community/pac.md, _public_services/eagles-nest.markdown, _sass/techhigh/cards.scss, _sass/techhigh/templates/faculty.scss, _student_life/clubs.markdown, _student_life/library.md
Faculty spacing has been fixed, front page image has been replaced to a placeholder image, library faculty links has been fixed, majority of club descriptions has been added, and some other grammatical fixes have been done.
=> A bunch of changes

_sass/techhigh/templates/department-pages.scss
Changed the background color for the summer work sections just to be safe about the new accessibility guidelines.
=> Department Pages update.

_data/faculty.csv, _layouts/academics.html, _parents_and_community/pac.md, _student_life/clubs.markdown
The merge branch dev commit was when I synced and pullled from it, it doesn't change anything.
Changes:
-Removed any instance of Allison Audet's name appearing and replacing it with the new MCAS Specialist, Jacquelyn Krull.
-Reverted the changes to the Club markdown page I made in the last pull request, like I said I would.
=> Small Changes.

_alden_academy/adv-manufacturing.md, _allied_academy/early-childhood.markdown, _includes/footer.html, _includes/header.html, _layouts/athletics.html, _layouts/contact-us.html, _layouts/events.html, _parents_and_community/pac.md, _public_services/skyline-bistro.md, _sass/techhigh/templates/contact-us.scss, _sass/techhigh/templates/faculty.scss, _sass/techhigh/text.scss, _sections/public-services.md, _student_life/athletics.md, index.md
There was a lot of small changes, there might be some leftover code through me experimenting, if there is let me know and I'll change it.
Changes:
-Fixed typos and mistakes in Advanced Manufacturing, Early Childhood, and Header.
-Replaced all instances of 7:20 to 7:16 in Footer, Contact Us, and Public Services.
-Changed the "today" in the calendar from lowercase to uppercase in Events.
-Centered text in PAC.
-Added alt text to two images in Skyline Bistro.
-Changed the SCSS for Contact Us to make the images bigger.
-Made headers for the Faculty page bigger.
-Made headers for every page (for example, Learn More or Faculty or Public Services)
-Changed the Athletics page to get rid of the Nurses and put the Coach field in their bio.
-Edited the index markdown page to show the faces of the …
=> Big things come in small packages!

_layouts/athletics.html, _sass/techhigh/templates/athletics.scss, _student_life/athletics.md
-Added calendar to athletics page
-Still need to update the font/sizes of Coach Contact Information
👍
=> Expanding Athletics

_student_life/athletics.md
-Fixed weird display of one of the cheer coaches at the top of the page
👍
=> more info in pr

_data/faculty.csv, _itbs_academy/webdev.markdown
=> Added Webdev Alumni

_itbs_academy/webdev.markdown, _sass/techhigh/hero.scss
Student Life banner is now centered so it looks good on desktop.
=> Fixed Student Life banner

_includes/components/collection-carousel.html, _includes/components/hero-carousel.html, _includes/footer.html, _includes/head.html, _includes/header.html, _includes/social.html, _includes/subheader.html, _layouts/clubs.html, _layouts/default.html, _layouts/events.html, _layouts/front-page.html, _layouts/tufts-at-tech.html, _public_services/skyline-bistro.md, _sass/style.scss, _sass/techhigh.scss, _sass/techhigh/cards.scss, _sass/techhigh/carousel.scss, _sass/techhigh/front-page/front-page.scss, _sass/techhigh/header.scss, _sass/techhigh/text.scss, _sass/underscores/components/navigation/_navigation.scss
Navbar was taken care of for Bootstrap, looking identical to the one on the live site. There are images on some pages that need to get resized but that'll be easy (just use width and height!), but the main problem is event carousels. Right now they look ugly, the images are stretched, and the vertical ones don't work, so that's the big problem right now.
=> Bootstrap Beginnings

_data/faculty.csv, _includes/header.html, _layouts/clubs.html, _layouts/contact-us.html, _layouts/print-shop.html, _parents_and_community/advisory.md, _sass/techhigh/cards.scss, _sass/techhigh/templates/public-services.scss
Some pages in Bootstrap have been fixed while some still need more work (like the Navbar while in mobile), the pages that were fixed were the clubs page, the admissions page, the graphics print shop page, and the contact us page.
=> More Bootstrap Additions

_config.yml, _includes/header.html, _sass/techhigh/header.scss
I've made changes according to Marketing's asks.
Changes: 
-Got rid of the highlight gray in the dropdown menu
-Centered text only on desktop
-Made search button smaller
-Changed color of text in dropdown menu
-Got rid of the dropdown options that have the same name as the category (too confusing for the viewer)
=> Bootstrap Navbar changes

_data/faculty.csv, _includes/footer.html, _layouts/clubs.html, _layouts/front-page.html, _sass/techhigh/cards.scss, _student_life/clubs.markdown
Changes:
**Logos**
- Changed the logo present on the Contact Us thumbnail and the bottom page header. Probably will have to change it back later though.
**Clubs**
- Changed box formatting, changed most of the text, added some new clubs, and deleted obsolete ones.
- _Currently, the page has a slight right-scroll problem with the Leadership section._
=> begin the techhigh image EXPLOSION!

_includes/components/collection-carousel.html, _includes/components/hero-carousel.html, _sass/techhigh/carousel.scss, _sass/techhigh/events.scss, _sass/techhigh/hero.scss, assets/js/carousel.js, index.md
As the title says, the event carousels are fully functional! The only thing that isn't here is the indicators for the events carousels (needs more work + it's 11 pm I'm tired). Once indicators have been added we'll be good to go for events carousels, the only things left would be putting all the new content into the bootstrap branch + some more navbar changes.
=> Bootstrap events carousels have been fixed(almost...)

_sass/techhigh/cards.scss, _student_life/clubs.markdown
Changes:
- Increased and decreased WAY too many things to name
- Fixed an issue where the page could scroll to the right.
- Made the cards centered
- Made the teachers' names lead to their email
=> club page final touches

_student_life/clubs.markdown
Change:
- Took out some unnecessary periods at the end of a few dates in the boxes.
=> club page extra fix

_layouts/clubs.html, _sass/techhigh/cards.scss
Change:
- Removed the text that was underneath the main club header.
=> club page text removal

_includes/components/collection-carousel.html, _includes/components/hero-carousel.html, _includes/header.html, _sass/techhigh/carousel.scss, _sass/techhigh/events.scss, _sass/techhigh/header.scss, assets/js/carousel.js
We are so close to pushing Bootstrap into production, the only things that need to be done are getting the indicators to work (I wanted to fix this but I got sick in the second half of the break and uh, couldn't get to it) and then getting the content up to date with the dev version, THAT'S IT. I've found simpler ways to do what's already been done while changing the Navbar to feel more responsive, as well as made it so no matter what the slides are synced.
=> Thanksgiving Break Coding

_config.yml, _includes/components/collection-carousel.html, _includes/scripts.html, _layouts/default.html, assets/js/navigation-obs.js, assets/js/navigation.js, assets/js/slideshow copy.js
Minor tweaks. Should be good now.
=> indicators fixed, commented obs scripts

_layouts/admissions.html, _layouts/principal.html, _learn_more/admissions.md, _sass/techhigh/cards.scss, _sass/techhigh/footer.scss, _sass/techhigh/templates/principal.scss, _sass/techhigh/templates/public-services.scss
Changes:
- Made some syntax easier to read (mostly just adding spaces between curly braces and regular text)
- Changed some text n the Admissions page.
=> admissions page and some syntax readability

_layouts/admissions.html, _learn_more/admissions.md, _sass/techhigh/templates/admission.scss
**Changes**
- Brought back the video placeholder, and commented out the blue border around it.
- Changed the dates and times to be up to date.
=> admissions page mk2: return of finance and marketing

_layouts/admissions.html
**Change**
- Added the link to Go2CTE.com on the respective text box.
=> added the link to Go2CTE

_academics/special-ed.md, _layouts/special-ed.html, _sass/techhigh/templates/department-pages.scss
There was an issue that displayed no content in the Special Ed page but also messed up the other academics pages, but it's now fixed.
=> Fixed no content in Special Ed page.

_layouts/admissions.html, _sass/techhigh/templates/admission.scss
**Changes**
- Increased the size of the Eagle picture in the video placeholder
- Made the color of the link text accurate
- made the link text not turn purple when its clicked
=> tweaked admissions page

_data/faculty.csv, _layouts/events.html, _layouts/front-page.html, _sass/techhigh/cards.scss
There's no big changes, just making sure all the small bugs are fixed.
Change List:
-Updated CSV file
-Fixed cards on front page to show text when hovered over.
-Fixed Events calendar to look the same as the athletics one on mobile as before it had no aspect ratio or content height.
=> Mobile and Desktop Fixes.

_data/faculty.csv, _sass/techhigh.scss, _sass/techhigh/templates/department-pages.scss, _sass/techhigh/templates/library.scss, _student_life/library.html
I added classes and a scss file for the Library page to make it fit in with the design of the website as well as following Finance's design.
=> Made changes to Library page.

_data/faculty.csv, _layouts/admissions.html, _layouts/contact-us.html, _sass/techhigh/templates/admission.scss, _student_life/library.html
I added in comments to the JS on the Admissions page and also, for some reason, the emails on that page where made white, for some reason, I fixed that as well.
=> Minor Things.

_sass/techhigh/templates/department-pages.scss
**Change**
- Added $color:primary for departments-page.scss
=> change i forgot to commit with primary color

_layouts/faculty.html, _sass/techhigh/templates/faculty.scss
**Change:**
- Fixed search feature from Nick's pull request
- Staff boxes now disappear properly when filtered out, and reappear as well.
- Search bar changes size depending on screen size (hooray! mobile!)
=> The End of the Faculty Search Feature

_includes/header.html, index.md
Search needs to be investigated but it's building the site now.
=> Fixed compatibility
